const char* parrot[] = {
"                        .cccc;;cc;';c.\n"
"                      .,:dkdc:;;:c:,:d:.\n"
"                     .loc'.,cc::::::,..,:.\n"
"                   .cl;....;dkdccc::,...c;\n"
"                  .c:,';:'..ckc',;::;....;c.\n"
"                .c:'.,dkkoc:ok:;llllc,,c,';:.\n"
"               .;c,';okkkkkkkk:,lllll,:kd;.;:,.\n"
"               co..:kkkkkkkkkk:;llllc':kkc..oNc\n"
"             .cl;.,okkkkkkkkkkc,:cll;,okkc'.cO;\n"
"             ;k:..ckkkkkkkkkkkl..,;,.;xkko:',l'\n"
"            .,...';dkkkkkkkkkkd;.....ckkkl'.cO;\n"
"         .,,:,.;oo:ckkkkkkkkkkkdoc;;cdkkkc..cd,\n"
"      .cclo;,ccdkkl;llccdkkkkkkkkkkkkkkkd,.c;\n"
"     .lol:;;okkkkkxooc::loodkkkkkkkkkkkko'.oc\n"
"   .c:'..lkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkd,.oc\n"
"  .lo;,ccdkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkd,.c;\n"
",dx:..;lllllllllllllllllllllllllllllllloc'...\n"
"cNO;........................................\n",

"                .ckx;'........':c.\n"
"             .,:c:c:::oxxocoo::::,',.\n"
"            .odc'..:lkkoolllllo;..;d,\n"
"            ;c..:o:..;:..',;'.......;.\n"
"           ,c..:0Xx::o:.,cllc:,'::,.,c.\n"
"           ;c;lkXXXXXXl.;lllll;lXXOo;':c.\n"
"         ,dc.oXXXXXXXXl.,lllll;lXXXXx,c0:\n"
"         ;Oc.oXXXXXXXXo.':ll:;'oXXXXO;,l'\n"
"         'l;;OXXXXXXXXd'.'::'..dXXXXO;,l'\n"
"         'l;:0XXXXXXXX0x:...,:o0XXXXk,:x,\n"
"         'l;;kXXXXXXKXXXkol;oXXXXXXXO;oNc\n"
"        ,c'..ckk0XXXXXXXXXX00XXXXXXX0:;o:.\n"
"      .':;..:dd::ooooOXXXXXXXXXXXXXXXo..c;\n"
"    .',',:co0XX0kkkxx0XXXXXXXXXXXXXXX0c..;l.\n"
"  .:;'..oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXko;';:.\n"
".cdc..:oOXXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXo..oc\n"
":0o...:dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo,.:,\n"
"cNo........................................;'\n",

"           .cc;.  ...  .;c.\n"
"        .,,cc:cc:lxxxl:ccc:;,.\n"
"       .lo;...lKKklllookl..cO;\n"
"     .cl;.,;'.okl;...'.;,..';:.\n"
"    .:o;;dkx,.ll..,cc::,..,'.;:,.\n"
"    co..lKKKkokl.':lllo;''ol..;dl.\n"
"  .,c;.,xKKKKKKo.':llll;.'oOxo,.cl,.\n"
"  cNo..lKKKKKKKo'';llll;;okKKKl..oNc\n"
"  cNo..lKKKKKKKko;':c:,'lKKKKKo'.oNc\n"
"  cNo..lKKKKKKKKKl.....'dKKKKKxc,l0:\n"
"  .c:'.lKKKKKKKKKk;....oKKKKKKo'.oNc\n"
"    ,:.,oxOKKKKKKKOxxxxOKKKKKKxc,;ol:.\n"
"    ;c..'':oookKKKKKKKKKKKKKKKKKk:.'clc.\n"
"  ,dl'.,oxo;'';oxOKKKKKKKKKKKKKKKOxxl::;,,.\n"
" .dOc..lKKKkoooookKKKKKKKKKKKKKKKKKKKxl,;ol.\n"
" cx,';okKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKl..;lc.\n"
" co..:dddddddddddddddddddddddddddddddddl:;''::.\n"
" co...........................................\"\n",

"           .ccccccc.\n"
"      .,,,;cooolccol;;,,.\n"
"     .dOx;..;lllll;..;xOd.\n"
"   .cdo,',loOXXXXXkll;';odc.\n"
"  ,oo:;c,':oko:cccccc,...ckl.\n"
"  ;c.;kXo..::..;c::'.......oc\n"
",dc..oXX0kk0o.':lll;..cxxc.,ld,\n"
"kNo.'oXXXXXXo'':lll;..oXXOd;cOd.\n"
"KOc;oOXXXXXXo.':lol,..dXXXXl';xc\n"
"Ol,:k0XXXXXX0c.,clc'.:0XXXXx,.oc\n"
"KOc;dOXXXXXXXl..';'..lXXXXXd..oc\n"
"dNo..oXXXXXXXOx:..'lxOXXXXXk,.:; ..\n"
"cNo..lXXXXXXXXXOolkXXXXXXXXXkl;..;:.;.\n"
".,;'.,dkkkkk0XXXXXXXXXXXXXXXXXOxxl;,;,;l:.\n"
"  ;c.;:''''':doOXXXXXXXXXXXXXXXXXXOdo;';clc.\n"
"  ;c.lOdood:'''oXXXXXXXXXXXXXXXXXXXXXk,..;ol.\n"
"  ';.:xxxxxocccoxxxxxxxxxxxxxxxxxxxxxxl::'.';;.\n"
"  ';........................................;l'\n",

"\n"
"       .;:;;,.,;;::,.\n"
"    .;':;........'co:.\n"
"  .clc;'':cllllc::,.':c.\n"
" .lo;;o:coxdlooollc;',::,,.\n"
"c:'.,cl,.'lc',,;;'......cO;\n"
"o;';oxoc::l;;llllc'.';;'.';.\n"
"..ckkkkkkkd,;llllc'.:kkd;.':c.\n"
".,okkkkkkkkc;llllc,.:kkkdl,cO;\n"
".;xkkkkkkkkc,ccll:,;okkkkk:,cl,\n"
".,dkkkkkkkkc..,;,'ckkkkkkkc;ll.\n"
".'okkkkkkkko,....'okkkkkkkc,:c.\n"
"..ckkkkkkkkkdl;,:okkkkkkkkd,.',';.\n"
"..':lxkkkkkkkkxxkkkkkkkkkkkdoc;,;'..'.,.\n"
"...'';llllldkkkkkkkkkkkkkkkkkkdll;..'cdo.\n"
"..,l;'''''';dkkkkkkkkkkkkkkkkkkkkdlc,..;lc.\n"
"..;lc;;;;;;,,;clllllllllllllllllllllc'..,:c.\n"
"..........................................;'\n",


"           .,,,,,,,,,.\n"
"         .ckKxodooxOOdcc.\n"
"      .cclooc'....';;cool.\n"
"     .loc;;;;clllllc;;;;;:;,.\n"
"   .c:'.,okd;;cdo:::::cl,..oc\n"
"  .:o;';okkx;';;,';::;'....,;,.\n"
"  co..ckkkkkddk:,cclll;.,c:,:o:.\n"
"  co..ckkkkkkkk:,cllll;.:kkd,.':c.\n"
".,:;.,okkkkkkkk:,cclll;.:kkkdl;;o:.\n"
"cNo..ckkkkkkkkko,.;llc,.ckkkkkc..oc\n"
",dd;.:kkkkkkkkkx;..;:,.'lkkkkko,.:,\n"
"  ;c.ckkkkkkkkkkc.....;ldkkkkkk:.,'\n"
",dc..'okkkkkkkkkxoc;;cxkkkkkkkkc..,;,.\n"
"kNo..':lllllldkkkkkkkkkkkkkkkkkdcc,.;l.\n"
"KOc,l;''''''';lldkkkkkkkkkkkkkkkkkc..;lc.\n"
"xx:':;;;;,.,,...,;;cllllllllllllllc;'.;oo,\n"
"cNo.....................................oc\n",

"\n"
"\n"
"                   .ccccccc.\n"
"               .ccckNKOOOOkdcc.\n"
"            .;;cc:ccccccc:,::::,,.\n"
"         .c;:;.,cccllxOOOxlllc,;ol.\n"
"        .lkc,coxo:;oOOxooooooo;..:,\n"
"      .cdc.,dOOOc..cOd,.',,;'....':c.\n"
"      cNx'.lOOOOxlldOl..;lll;.....cO;\n"
"     ,do;,:dOOOOOOOOOl'':lll;..:d:.'c,\n"
"     co..lOOOOOOOOOOOl'':lll;.'lOd,.cd.\n"
"     co.,dOOOOOOOOOOOo,.;llc,.,dOOc..dc\n"
"     co..lOOOOOOOOOOOOc.';:,..cOOOl..oc\n"
"   .,:;.'::lxOOOOOOOOOo:'...,:oOOOc..dc\n"
"   ;Oc..cl'':llxOOOOOOOOdcclxOOOOx,.cd.\n"
"  .:;';lxl''''':lldOOOOOOOOOOOOOOc..oc\n"
",dl,.'cooc:::,....,::coooooooooooc'.c:\n"
"cNo.................................oc\n",

"\n"
"\n"
"\n"
"                        .cccccccc.\n"
"                  .,,,;;cc:cccccc:;;,.\n"
"                .cdxo;..,::cccc::,..;l.\n"
"               ,oo:,,:c:cdxxdllll:;,';:,.\n"
"             .cl;.,oxxc'.,cc,.',;;'...oNc\n"
"             ;Oc..cxxxc'.,c;..;lll;...cO;\n"
"           .;;',:ldxxxdoldxc..;lll:'...'c,\n"
"           ;c..cxxxxkxxkxxxc'.;lll:'','.cdc.\n"
"         .c;.;odxxxxxxxxxxxd;.,cll;.,l:.'dNc\n"
"        .:,''ccoxkxxkxxxxxxx:..,:;'.:xc..oNc\n"
"      .lc,.'lc':dxxxkxxxxxxxdl,...',lx:..dNc\n"
"     .:,',coxoc;;ccccoxxxxxxxxo:::oxxo,.cdc.\n"
"  .;':;.'oxxxxxc''''';cccoxxxxxxxxxkxc..oc\n"
",do:'..,:llllll:;;;;;;,..,;:lllllllll;..oc\n"
"cNo.....................................oc\n",

"\n"
"\n"
"                             .ccccc.\n"
"                        .cc;'coooxkl;.\n"
"                    .:c:::c:,;,,,;c;;,.'.\n"
"                  .clc,',:,..:xxocc;...c;\n"
"                 .c:,';:ox:..:c,,,,,,...cd,\n"
"               .c:'.,oxxxxl::l:.;loll;..;ol.\n"
"               ;Oc..:xxxxxxxxx:.,llll,....oc\n"
"            .,;,',:loxxxxxxxxx:.,llll;.,;.'ld,\n"
"           .lo;..:xxxxxxxxxxxx:.'cllc,.:l:'cO;\n"
"          .:;...'cxxxxxxxxxxxxol;,::,..cdl;;l'\n"
"        .cl;':;'';oxxxxxxxxxxxxx:....,cooc,cO;\n"
"    .,,,::;,lxoc:,,:lxxxxxxxxxxxo:,,;lxxl;'oNc\n"
"  .cdxo;':lxxxxxxc'';cccccoxxxxxxxxxxxxo,.;lc.\n"
" .loc'.'lxxxxxxxxocc;''''';ccoxxxxxxxxx:..oc\n"
"cc'..',:cccccccccccc:;;;;;;;;:ccccccccc,.'c,\n"
"l;......................................;l'\n",

"\n"
"                              ,ddoodd,\n"
"                         .cc' ,ooccoo,'cc.\n"
"                      .ccldo;....,,...;oxdc.\n"
"                   .,,:cc;.''..;lol;;,'..lkl.\n"
"                  .dkc';:ccl;..;dl,.''.....oc\n"
"                .,lc',cdddddlccld;.,;c::'..,cc:.\n"
"                cNo..:ddddddddddd;':clll;,c,';xc\n"
"               .lo;,clddddddddddd;':clll;:kc..;'\n"
"             .,:;..:ddddddddddddd:';clll;;ll,..\n"
"             ;Oc..';:ldddddddddddl,.,c:;';dd;..\n"
"           .''',:lc,'cdddddddddddo:,'...'cdd;..\n"
"         .cdc';lddd:';lddddddddddddd;.';lddl,..\n"
"      .,;::;,cdddddol;;lllllodddddddlcodddd:.'l,\n"
"     .dOc..,lddddddddlccc;'';cclddddddddddd;,ll.\n"
"   .coc,;::ldddddddddddddl:ccc:ldddddddddlc,ck;\n"
",dl::,..,cccccccccccccccccccccccccccccccc:;':xx,\n"
"cNd.........................................;lOc\n",
NULL
};
