name: Build RanaOS ISO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          binutils \
          nasm \
          g++ \
          grub-pc-bin \
          xorriso \
          qemu-system-i386

    - name: Build ISO image
      run: make

    - name: Verify ISO image was created
      run: |
        if [ ! -f RanaOS.iso ]; then
          echo "Error: RanaOS.iso was not created"
          exit 1
        fi
        echo "ISO image created successfully: RanaOS.iso"

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: RanaOS.iso
        path: RanaOS.iso

