name: Build .iso

on:
  workflow_dispatch:

jobs:
  build-msi-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build ISO
      run: |
        make
      
    
    - name: Upload .iso
      uses: actions/upload-artifact@v4
      with:
        name: RanaOS
        path: |
          RanaOS.iso
